version: '3.8'

services:
  app:
    container_name: DATN-cms-customer
    build:
      context: .
      dockerfile: .docker/Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/anhhuy1010/DATN-cms-customer
    ports:
      - 7003:7003
      - 9003:9003
    networks:
      - datn_net
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  datn_net:
