version: '3.8'

services:
  app:
    container_name: DATN-cms-customer
    build:
      context: .
      dockerfile: .docker/Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/anhhuy1010/DATN-cms-customer
    ports:
      - 7003:7003
      - 9003:9003
    networks:
      - datn_net
    dns:
      - 8.8.8.8
      - 8.8.4.4

  customer-service:
    image: registry.heroku.com/imatching/web:latest
    ports:
      - 8080:8080
    networks:
      - datn_net

networks:
  datn_net:
