// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: updatecustomer.proto

/*
Package updatecustomer is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package updatecustomer

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_UpdateCustomer_UpdateDuration_0(ctx context.Context, marshaler runtime.Marshaler, client UpdateCustomerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq UpdateDurationRequest
		metadata runtime.ServerMetadata
		err      error
	)
	io.Copy(io.Discard, req.Body)
	val, ok := pathParams["uuid"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "uuid")
	}
	protoReq.Uuid, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "uuid", err)
	}
	msg, err := client.UpdateDuration(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_UpdateCustomer_UpdateDuration_0(ctx context.Context, marshaler runtime.Marshaler, server UpdateCustomerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq UpdateDurationRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["uuid"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "uuid")
	}
	protoReq.Uuid, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "uuid", err)
	}
	msg, err := server.UpdateDuration(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterUpdateCustomerHandlerServer registers the http handlers for service UpdateCustomer to "mux".
// UnaryRPC     :call UpdateCustomerServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterUpdateCustomerHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterUpdateCustomerHandlerServer(ctx context.Context, mux *runtime.ServeMux, server UpdateCustomerServer) error {
	mux.Handle(http.MethodGet, pattern_UpdateCustomer_UpdateDuration_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/customer.UpdateCustomer/UpdateDuration", runtime.WithHTTPPathPattern("/v1/customers/{uuid}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_UpdateCustomer_UpdateDuration_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_UpdateCustomer_UpdateDuration_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterUpdateCustomerHandlerFromEndpoint is same as RegisterUpdateCustomerHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterUpdateCustomerHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterUpdateCustomerHandler(ctx, mux, conn)
}

// RegisterUpdateCustomerHandler registers the http handlers for service UpdateCustomer to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterUpdateCustomerHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterUpdateCustomerHandlerClient(ctx, mux, NewUpdateCustomerClient(conn))
}

// RegisterUpdateCustomerHandlerClient registers the http handlers for service UpdateCustomer
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "UpdateCustomerClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "UpdateCustomerClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "UpdateCustomerClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterUpdateCustomerHandlerClient(ctx context.Context, mux *runtime.ServeMux, client UpdateCustomerClient) error {
	mux.Handle(http.MethodGet, pattern_UpdateCustomer_UpdateDuration_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/customer.UpdateCustomer/UpdateDuration", runtime.WithHTTPPathPattern("/v1/customers/{uuid}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_UpdateCustomer_UpdateDuration_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_UpdateCustomer_UpdateDuration_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_UpdateCustomer_UpdateDuration_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "customers", "uuid"}, ""))
)

var (
	forward_UpdateCustomer_UpdateDuration_0 = runtime.ForwardResponseMessage
)
