// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: updatecustomer.proto

package updatecustomer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDurationRequest) Reset() {
	*x = UpdateDurationRequest{}
	mi := &file_updatecustomer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDurationRequest) ProtoMessage() {}

func (x *UpdateDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updatecustomer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDurationRequest) Descriptor() ([]byte, []int) {
	return file_updatecustomer_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDurationRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UpdateDurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDurationResponse) Reset() {
	*x = UpdateDurationResponse{}
	mi := &file_updatecustomer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDurationResponse) ProtoMessage() {}

func (x *UpdateDurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updatecustomer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDurationResponse) Descriptor() ([]byte, []int) {
	return file_updatecustomer_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDurationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_updatecustomer_proto protoreflect.FileDescriptor

const file_updatecustomer_proto_rawDesc = "" +
	"\n" +
	"\x14updatecustomer.proto\x12\bcustomer\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\x15UpdateDurationRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"2\n" +
	"\x16UpdateDurationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2}\n" +
	"\bCustomer\x12q\n" +
	"\x0eUpdateDuration\x12\x1f.customer.UpdateDurationRequest\x1a .customer.UpdateDurationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/customers/{uuid}BCZAgithub.com/anhhuy1010/DATN-cms-customer/grpc/proto/updatecustomerb\x06proto3"

var (
	file_updatecustomer_proto_rawDescOnce sync.Once
	file_updatecustomer_proto_rawDescData []byte
)

func file_updatecustomer_proto_rawDescGZIP() []byte {
	file_updatecustomer_proto_rawDescOnce.Do(func() {
		file_updatecustomer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updatecustomer_proto_rawDesc), len(file_updatecustomer_proto_rawDesc)))
	})
	return file_updatecustomer_proto_rawDescData
}

var file_updatecustomer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_updatecustomer_proto_goTypes = []any{
	(*UpdateDurationRequest)(nil),  // 0: customer.UpdateDurationRequest
	(*UpdateDurationResponse)(nil), // 1: customer.UpdateDurationResponse
}
var file_updatecustomer_proto_depIdxs = []int32{
	0, // 0: customer.Customer.UpdateDuration:input_type -> customer.UpdateDurationRequest
	1, // 1: customer.Customer.UpdateDuration:output_type -> customer.UpdateDurationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_updatecustomer_proto_init() }
func file_updatecustomer_proto_init() {
	if File_updatecustomer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updatecustomer_proto_rawDesc), len(file_updatecustomer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_updatecustomer_proto_goTypes,
		DependencyIndexes: file_updatecustomer_proto_depIdxs,
		MessageInfos:      file_updatecustomer_proto_msgTypes,
	}.Build()
	File_updatecustomer_proto = out.File
	file_updatecustomer_proto_goTypes = nil
	file_updatecustomer_proto_depIdxs = nil
}
