// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: updatecustomer.proto

package updatecustomer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateCustomer_UpdateDuration_FullMethodName = "/customer.UpdateCustomer/UpdateDuration"
)

// UpdateCustomerClient is the client API for UpdateCustomer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateCustomerClient interface {
	UpdateDuration(ctx context.Context, in *UpdateDurationRequest, opts ...grpc.CallOption) (*UpdateDurationResponse, error)
}

type updateCustomerClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateCustomerClient(cc grpc.ClientConnInterface) UpdateCustomerClient {
	return &updateCustomerClient{cc}
}

func (c *updateCustomerClient) UpdateDuration(ctx context.Context, in *UpdateDurationRequest, opts ...grpc.CallOption) (*UpdateDurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDurationResponse)
	err := c.cc.Invoke(ctx, UpdateCustomer_UpdateDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateCustomerServer is the server API for UpdateCustomer service.
// All implementations must embed UnimplementedUpdateCustomerServer
// for forward compatibility.
type UpdateCustomerServer interface {
	UpdateDuration(context.Context, *UpdateDurationRequest) (*UpdateDurationResponse, error)
	mustEmbedUnimplementedUpdateCustomerServer()
}

// UnimplementedUpdateCustomerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateCustomerServer struct{}

func (UnimplementedUpdateCustomerServer) UpdateDuration(context.Context, *UpdateDurationRequest) (*UpdateDurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDuration not implemented")
}
func (UnimplementedUpdateCustomerServer) mustEmbedUnimplementedUpdateCustomerServer() {}
func (UnimplementedUpdateCustomerServer) testEmbeddedByValue()                        {}

// UnsafeUpdateCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateCustomerServer will
// result in compilation errors.
type UnsafeUpdateCustomerServer interface {
	mustEmbedUnimplementedUpdateCustomerServer()
}

func RegisterUpdateCustomerServer(s grpc.ServiceRegistrar, srv UpdateCustomerServer) {
	// If the following call pancis, it indicates UnimplementedUpdateCustomerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateCustomer_ServiceDesc, srv)
}

func _UpdateCustomer_UpdateDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateCustomerServer).UpdateDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateCustomer_UpdateDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateCustomerServer).UpdateDuration(ctx, req.(*UpdateDurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateCustomer_ServiceDesc is the grpc.ServiceDesc for UpdateCustomer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateCustomer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer.UpdateCustomer",
	HandlerType: (*UpdateCustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDuration",
			Handler:    _UpdateCustomer_UpdateDuration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "updatecustomer.proto",
}
